apiVersion: v1
kind: LimitRange
metadata:
  name: vprofile-limits
  namespace: vprofile
spec:
  limits:
  - default:
      cpu: "1000m"
      memory: "1Gi"
    defaultRequest:
      cpu: "250m"
      memory: "512Mi"
    max:
      cpu: "4000m"
      memory: 4Gi
    min:
      cpu: "10m"
      memory: "16Mi"
    type: Container
  - max:
      storage: 20Gi
    type: PersistentVolumeClaim
