apiVersion: v1
kind: ResourceQuota
metadata:
  name: vprofile-quota
  namespace: vprofile
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    pods: "20"
    services: "15"
